[browser]
gatherUsageStats = false

[server]
address = "localhost"

[client]
toolbarMode = "minimal"

[theme]
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
codeFont = "JetBrains Mono:https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&display=swap"
baseFontSize = 14
headingFontWeights = [700, 600]
baseRadius = "0.6rem"
showWidgetBorder = true
showSidebarBorder = true

[theme.light]
primaryColor = "#0051ff"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f6ff"
textColor = "#1c355e"
borderColor = "#d8e4f7"
dataframeBorderColor = "#d8e4f7"
chartCategoricalColors = ["#0051ff", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7", "#e34948"]
chartSequentialColors = ["#dde8fe", "#c9dbfe", "#b5cefe", "#9cbefe", "#83adfe", "#4b85fe", "#0051ff", "#0043de", "#0036ba", "#002693"]

[theme.light.sidebar]
backgroundColor = "#f7faff"
secondaryBackgroundColor = "#e7f0ff"

[theme.dark]
primaryColor = "#4b85fe"
backgroundColor = "#0a1a30"
secondaryBackgroundColor = "#12243f"
textColor = "#ffffff"
borderColor = "#1e3554"
dataframeBorderColor = "#1e3554"
chartCategoricalColors = ["#4b85fe", "#d95926", "#199e70", "#c98500", "#d55181", "#008300", "#9085e9", "#e66767"]
chartSequentialColors = ["#001775", "#002693", "#0036ba", "#0043de", "#0051ff", "#296cff", "#4b85fe", "#699bff", "#83adfe", "#9cbefe"]

[theme.dark.sidebar]
backgroundColor = "#081426"
secondaryBackgroundColor = "#12243f"
